name: gym_buddies
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase dependencies (USE LATEST VERSIONS - CHECK PUB.DEV)
  firebase_core: ^3.12.0  # Replace with the latest version
  firebase_auth: ^5.5.1   # Replace with the latest version
  cloud_firestore: ^5.6.0  # Replace with the latest version

  intl: ^0.19.0
  shared_preferences: ^2.3.2
  fl_chart: ^0.70.2
  month_year_picker: ^0.4.0+1
  pedometer: 4.0.2
  provider: ^6.0.0
  syncfusion_flutter_charts: ^29.1.33
  #image_picker: ^1.0.7
  #http: ^1.3.0
  #google_generative_ai: ^0.4.6 # Use the latest version
  #crypto: ^3.0.6 # Or the latest version
  # Add any other dependencies your app needs here

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0 # Upgraded to the latest version
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/yoga_logo.png
    - assets/cycling_logo.png
    - assets/gym.png
    - assets/yoga.png
    - assets/cycling.png
    - assets/jogging.png
    - assets/custom_programs.png
    - assets/Inventory.png
    #For costum Gym Program Page ----------------------------------------------------------------
    - assets/abs-workout-gym.png
    - assets/biceps-workout-gym.png
    - assets/back-workout-gym.png
    - assets/chest-workout-gym.png
    - assets/legs-workout-gym.png
    - assets/shoulders-workout-gym.png
    - assets/triceps-workout-gym.png
    - assets/bench_press.png
    #CustomP Programs Page---------------------------------------------------------------------------------------------
    - assets/custom-page/gym-program.png
    - assets/custom-page/yoga-program.png
    - assets/custom-page/cycling-program.png
    - assets/custom-page/jogging-program.png
    - assets/custom-page/caliesthenics-program.png
    - assets/custom-page/swimming-program.png
    - assets/custom-page/home-workout-program.png
    - assets/custom-page/boxing-program.png
    #YogaProgramSelectionPage--------------------------------------------------------------------------------------------
    - assets/yoga/yoga-first-page/hatha-yoga.png
    - assets/yoga/yoga-first-page/vinyasa-yoga.png
    - assets/yoga/yoga-first-page/ashtanga-yoga.png
    - assets/yoga/yoga-first-page/yin-yoga.png
    - assets/yoga/yoga-first-page/restorative-yoga.png
    - assets/yoga/yoga-first-page/power-yoga.png
    #CyclingImages-----------------------------------------------------------------------------------------------------------
    - assets/cycling/cycling-outdoor.png
    - assets/cycling/cycling-indoor.png

#   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package