name: gym_buddies
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Icon libraries
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.12.1  # Core Firebase package (compatible with your Flutter version)
  firebase_auth: ^5.5.1  # Firebase authentication (compatible)
  cloud_firestore: ^5.6.5  # Firestore (Latest stable version)

  # Other dependencies
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  fl_chart: ^0.70.2
  month_year_picker: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Recommended lints for good coding practices

flutter:
  uses-material-design: true

  # Asset folder
  assets:
    - assets/logo.png
    - assets/yoga_logo.png
    - assets/cycling_logo.png
    - assets/gym.png
    - assets/yoga.png
    - assets/cycling.png
    - assets/jogging.png
    - assets/custom_programs.png
    - assets/Inventory.png
    - assets/abs-workout-gym.png
    - assets/biceps-workout-gym.png
    - assets/back-workout-gym.png
    - assets/chest-workout-gym.png
    - assets/legs-workout-gym.png
    - assets/shoulders-workout-gym.png
    - assets/triceps-workout-gym.png
    - assets/bench_press.png
    - assets/custom-page/gym-program.png
    - assets/custom-page/yoga-program.png
    - assets/custom-page/cycling-program.png
    - assets/custom-page/jogging-program.png
    - assets/custom-page/caliesthenics-program.png
    - assets/custom-page/swimming-program.png
    - assets/custom-page/home-workout-program.png
    - assets/custom-page/boxing-program.png
